application: guardian-subscriptions
version: 23  #remember to update the s.prop14 in base.html if you update this version number
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: subscription.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^nginx
- ^node_modules
- ^static/bower_components
- ^static/scss